const data = [
    {
        "id": 8857,
        "size": 4,
        "hire_period_days": 14,
        "transport_cost": null,
        "per_tonne_cost": null,
        "price_before_vat": 216,
        "vat": 20,
        "postcode": "LE10",
        "area": "Hinckley",
        "forbidden": false,
        "created_at": "2021-04-06T17:04:42",
        "updated_at": "2023-04-03T10:43:36",
        "allowed_on_road": true,
        "allows_heavy_waste": true
    },
    {
        "id": 8858,
        "size": 5,
        "hire_period_days": 14,
        "transport_cost": null,
        "per_tonne_cost": null,
        "price_before_vat": 260,
        "vat": 20,
        "postcode": "LE10",
        "area": "Hinckley",
        "forbidden": false,
        "created_at": "2021-04-06T17:04:42",
        "updated_at": "2023-04-03T10:43:36",
        "allowed_on_road": true,
        "allows_heavy_waste": true
    },
    {
        "id": 19046,
        "size": 6,
        "hire_period_days": 14,
        "transport_cost": null,
        "per_tonne_cost": null,
        "price_before_vat": 296,
        "vat": 20,
        "postcode": "LE10",
        "area": "Nuneaton",
        "forbidden": false,
        "created_at": "2022-11-16T09:48:07",
        "updated_at": "2024-04-02T09:25:50",
        "allowed_on_road": true,
        "allows_heavy_waste": true
    },
    {
        "id": 8859,
        "size": 8,
        "hire_period_days": 14,
        "transport_cost": null,
        "per_tonne_cost": null,
        "price_before_vat": 294,
        "vat": 20,
        "postcode": "LE10",
        "area": "Hinckley",
        "forbidden": false,
        "created_at": "2021-04-06T17:04:42",
        "updated_at": "2023-04-03T10:43:36",
        "allowed_on_road": true,
        "allows_heavy_waste": true
    },
    {
        "id": 8860,
        "size": 10,
        "hire_period_days": 14,
        "transport_cost": null,
        "per_tonne_cost": null,
        "price_before_vat": 369,
        "vat": 20,
        "postcode": "LE10",
        "area": "Hinckley",
        "forbidden": false,
        "created_at": "2021-04-06T17:04:42",
        "updated_at": "2023-04-03T10:43:36",
        "allowed_on_road": false,
        "allows_heavy_waste": false
    },
    {
        "id": 8861,
        "size": 12,
        "hire_period_days": 14,
        "transport_cost": null,
        "per_tonne_cost": null,
        "price_before_vat": 407,
        "vat": 20,
        "postcode": "LE10",
        "area": "Hinckley",
        "forbidden": false,
        "created_at": "2021-04-06T17:04:42",
        "updated_at": "2023-04-03T10:43:36",
        "allowed_on_road": false,
        "allows_heavy_waste": false
    },
    {
        "id": 8862,
        "size": 14,
        "hire_period_days": 14,
        "transport_cost": null,
        "per_tonne_cost": null,
        "price_before_vat": 477,
        "vat": 20,
        "postcode": "LE10",
        "area": "Hinckley",
        "forbidden": false,
        "created_at": "2021-04-06T17:04:42",
        "updated_at": "2023-04-03T10:43:36",
        "allowed_on_road": false,
        "allows_heavy_waste": false
    },
    {
        "id": 19720,
        "size": 16,
        "hire_period_days": 7,
        "transport_cost": null,
        "per_tonne_cost": null,
        "price_before_vat": 571,
        "vat": 20,
        "postcode": "LE10",
        "area": "Leicester",
        "forbidden": false,
        "created_at": "2023-06-28T09:58:34",
        "updated_at": "2024-04-02T09:26:07",
        "allowed_on_road": false,
        "allows_heavy_waste": false
    },
    {
        "id": 8863,
        "size": 20,
        "hire_period_days": 14,
        "transport_cost": 172,
        "per_tonne_cost": 197,
        "price_before_vat": 763,
        "vat": 20,
        "postcode": "LE10",
        "area": "Hinckley",
        "forbidden": false,
        "created_at": "2021-04-06T17:04:42",
        "updated_at": "2023-04-03T10:43:36",
        "allowed_on_road": false,
        "allows_heavy_waste": true
    },
    {
        "id": 8864,
        "size": 40,
        "hire_period_days": 14,
        "transport_cost": 172,
        "per_tonne_cost": 221,
        "price_before_vat": 836,
        "vat": 20,
        "postcode": "LE10",
        "area": "Hinckley",
        "forbidden": false,
        "created_at": "2021-04-06T17:04:42",
        "updated_at": "2023-04-03T10:43:36",
        "allowed_on_road": false,
        "allows_heavy_waste": false
    }
];

const location = [
    {
        "id": 914,
        "council_permit_days": 7,
        "council_permit_clear_working_days": 5,
        "price_before_vat": 84,
        "postcode": "LE10",
        "area": "Hinckley",
        "forbidden": false,
        "created_at": "2020-09-07T17:49:47",
        "updated_at": "2023-04-03T10:48:17"
    }
];